### PR TITLE
Ace Install

### PR DESCRIPTION
**Pull request by trevormorse**
Added instructions for install the Ace submodule if someone will be using the admin interface.

### CODE REVIEW

**Comment by trevormorse** [comment]
Ignore this, I was missing @dshafik change to check for ace and display error message if its missing.

**Comment by dshafik** [comment]
@trevormorse Other than the fact this text is specifically geared towards just the ace sub module and not sub modules in general, I think this text should be in the installation manual. Would you mind making that change and recreating the PR?

**Comment by trevormorse** [comment]
@dshafik Will do!

**Comment by trevormorse** [comment]
@dshafik Looks like you already have this covered in one of your previous pull requests :-) https://github.com/frapi/frapi.github.com/pull/5

**Pull request closed without merging**
